### ISSUE TITLE
考虑使用ActivityPub

### ISSUE THREAD

**Issue by drHuangMHT** [CatkatPowered/kat-protocol#2]
鉴于KatProtocol与ActivityPub的内容高度重合，私以为使用ActivityPub会是一种更好的选择。  
ActivityPub是 [W3C Recommendation](https://www.w3.org/TR/activitypub/)  
目前已知使用ActivityPub的项目有Mastodon和PeerTube。
既然使用KatProtocol是为了统一消息格式，为什么不使用已经获得认可的ActivityPub？
如果使用KatProtocol有别的好处，那也可以从ActivityPub中获得一些灵感。

**Comment by CatMoe** [comment]
？麻烦您先了解下我们在干什么好么
